import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
const id='G-5CTT86CCQ2'; // Public measurement ID; not a secret or an API key.
const version=createHash('sha256').update(readFileSync(new URL('../public/analytics.js',import.meta.url))).update(readFileSync(new URL('../public/measurement-core.js',import.meta.url))).digest('hex').slice(0,12);
const copy={
  fr:{title:'Votre choix de confidentialité',body:'Avec votre accord, Google Analytics nous aide à mesurer les visites et les demandes reçues. Aucun nom, e-mail, téléphone ou message de formulaire n’est transmis à cet outil. Refuser ne change pas les services du site.',accept:'Accepter la mesure',refuse:'Refuser la mesure',settings:'Confidentialité : mes choix',more:'En savoir plus',heading:'Mesure d’audience facultative',policy:'Google Analytics est chargé uniquement après votre accord. Il mesure les pages consultées, les clics téléphone et WhatsApp et les demandes confirmées par notre serveur. Les clics ne constituent pas des ventes. Les champs des formulaires, les identifiants des demandes et les paramètres des adresses ne sont pas envoyés à Analytics. Google peut traiter des informations techniques et des identifiants de navigation. Les fonctions publicitaires sont désactivées. Votre choix et les cookies Analytics sont conservés au maximum six mois. Vous pouvez refuser ou retirer votre accord avec « Confidentialité : mes choix » en bas de chaque page. Le retrait supprime les cookies Analytics de ce site. Le thème clair/sombre est mémorisé séparément ; les champs des formulaires ne sont pas conservés dans le stockage du navigateur.',google:'Comment Google utilise les données'},
  en:{title:'Your privacy choice',body:'With your consent, Google Analytics helps us measure visits and received enquiries. No names, emails, phone numbers or form messages are sent to this tool. Declining does not affect the website’s services.',accept:'Allow measurement',refuse:'Decline measurement',settings:'Privacy: my choices',more:'Learn more',heading:'Optional audience measurement',policy:'Google Analytics loads only after you consent. It measures page views, phone and WhatsApp clicks and enquiries confirmed by our server. Clicks are not sales. Form fields, request identifiers and URL parameters are not sent to Analytics. Google may process technical information and browsing identifiers. Advertising features are disabled. Your choice and Analytics cookies last for up to six months. You can decline or withdraw consent using “Privacy: my choices” in the footer. Withdrawal removes this site’s Analytics cookies. The light/dark theme is remembered separately; form fields are not saved in browser storage.',google:'How Google uses data'},
  ar:{title:'اختيارك بشأن الخصوصية',body:'بموافقتك، يساعدنا Google Analytics على قياس الزيارات والطلبات المستلمة. لا نرسل إليه الأسماء أو البريد أو أرقام الهاتف أو رسائل الاستمارات. الرفض لا يؤثر على خدمات الموقع.',accept:'السماح بالقياس',refuse:'رفض القياس',settings:'الخصوصية: اختياراتي',more:'معرفة المزيد',heading:'قياس الزيارات الاختياري',policy:'لا يتم تحميل Google Analytics إلا بعد موافقتك. يقيس الصفحات المشاهدة والنقرات على الهاتف وواتساب والطلبات التي أكد خادمنا استلامها. النقرات ليست مبيعات. لا نرسل حقول الاستمارات أو معرّفات الطلبات أو معاملات عناوين الصفحات إلى Analytics. قد تعالج Google معلومات تقنية ومعرّفات التصفح. الميزات الإعلانية معطلة. يُحفظ اختيارك وملفات ارتباط Analytics لمدة أقصاها ستة أشهر. يمكنك الرفض أو سحب الموافقة من «الخصوصية: اختياراتي» أسفل كل صفحة، مما يحذف ملفات ارتباط Analytics لهذا الموقع. يُحفظ اختيار المظهر بشكل منفصل، ولا تُحفظ حقول الاستمارات في تخزين المتصفح.',google:'كيف تستخدم Google البيانات'}
};
export function addAnalytics($,lang,slug){
  const t=copy[lang];
  if(['cookies','privacy','politique-confidentialite'].includes(slug)){
    // Replace obsolete no-tracking statements, including their translated equivalents.
    const p=$('main p').filter((_,el)=>/aucun cookie publicitaire|no advertising cookies|لا يثبت الموقع|pas de publicité, de suivi|no advertising, audience tracking|لا يتضمن الموقع إعلانات/.test($(el).text()));
    p.prev('h2,h3').text(t.heading); p.text(t.policy);
    if(!p.length)$('main').append(`<section class="seo-content"><h2>${t.heading}</h2><p>${t.policy}</p></section>`);
    $('main').append(`<p class="seo-content"><a href="https://policies.google.com/technologies/partner-sites" rel="noopener noreferrer">${t.google}</a></p>`);
  }
  $('footer').append(`<div class="audience-footer"><button type="button" data-audience-settings>${t.settings}</button></div>`);
  $('body').append(`<section class="audience-consent" data-analytics-consent data-measurement-id="${id}" aria-labelledby="audience-title" hidden><h2 id="audience-title">${t.title}</h2><p>${t.body} <a href="/${lang}/cookies/">${t.more}</a></p><div><button type="button" data-audience-choice="denied">${t.refuse}</button><button type="button" data-audience-choice="granted">${t.accept}</button></div></section><script type="module" src="/analytics.js?v=${version}"></script>`);
}
