export const faqData = {
fr:[
['Accompagnement','Intervenez-vous dans tout le Maroc ?','Oui. Felexia accompagne les entrepreneurs et les investisseurs dans tout le Maroc. Indiquez votre ville d’implantation et vos besoins : nous définissons ensemble les modalités de l’accompagnement, à distance et selon les exigences de votre dossier.'],
['Création','Quelle forme juridique choisir pour mon projet ?','Le choix dépend notamment du nombre d’associés, de l’activité, de la gouvernance et des perspectives de développement. La SARL, la SARL à associé unique, la SA ou une implantation d’une société étrangère répondent à des besoins différents. Un échange permet de préciser les options pertinentes.'],
['Création','Puis-je entreprendre au Maroc si je réside à l’étranger ?','Nous accompagnons les investisseurs étrangers et les Marocains résidant à l’étranger. La faisabilité, les documents et les éventuelles autorisations se vérifient en fonction de votre activité et de votre situation.'],
['Création','Peut-on préparer la création à distance ?','Le cadrage du projet et la préparation du dossier peuvent commencer à distance. Les exigences de signature, de procuration et de présence éventuelle dépendent de votre dossier et des organismes concernés.'],
['Création','Quels documents faut-il préparer ?','Pour le premier échange, indiquez votre activité, la ville d’implantation, votre situation de résidence et le nombre d’associés. La liste des justificatifs sera ensuite précisée selon la structure retenue. Aucun document d’identité n’est demandé dans notre formulaire initial.'],
['Accompagnement','Quels sont les délais de création ?','Ils dépendent de la forme juridique, de la complétude du dossier, de l’activité et du traitement par les administrations. Le calendrier prévisionnel est étudié après analyse du projet ; aucun délai fixe n’est garanti sur ce site.'],
['Tarifs','Combien coûte l’accompagnement Felexia ?','Chaque mission fait l’objet d’un devis personnalisé. Le périmètre, les honoraires et les frais éventuels sont précisés avant votre engagement. Aucun paiement n’est demandé dans le formulaire de contact.'],
['Accompagnement','Pouvez-vous accompagner une société déjà créée ?','Oui. Les besoins peuvent concerner la fiscalité, la gestion, l’évolution de la société ou des formalités administratives. Présentez-nous la situation et le résultat souhaité pour définir une mission adaptée.'],
['Accompagnement','Quelle différence entre une filiale et une succursale ?','La filiale est une société distincte, détenue majoritairement par une société mère. La succursale est un établissement rattaché à la société mère. Les implications juridiques, fiscales et organisationnelles doivent être examinées selon le projet.'],
['Contact','Comment se déroule le premier échange ?','Vous décrivez votre projet et vos besoins. Nous clarifions les prochaines étapes et le périmètre envisageable. Une demande de rendez-vous n’est confirmée qu’après échange avec le cabinet.'],
['Contact','Dans quelles langues pouvons-nous échanger ?','Vous pouvez présenter votre projet en français, en anglais ou en arabe. Sélectionnez votre langue dans le formulaire pour préparer les échanges.'],
['Données','Comment sont utilisées les informations du formulaire ?','Elles servent à comprendre votre demande et à vous recontacter. Ne transmettez pas de pièces d’identité, d’informations bancaires ou de documents confidentiels dans le formulaire initial. Consultez la politique de confidentialité pour en savoir plus.']
],
en:[
['Support','Do you support projects throughout Morocco?','Yes. Felexia supports entrepreneurs and investors across Morocco. Tell us your intended location and needs so we can define how to work together, remotely and according to the requirements of your file.'],
['Formation','Which business structure is right for my project?','The choice depends on the number of partners, business activity, governance and growth plans. An SARL, single-member SARL, SA or establishment of a foreign company serves different needs. A conversation helps identify the relevant options.'],
['Formation','Can I start a business in Morocco while living abroad?','We support foreign investors and Moroccans living abroad. Feasibility, documents and any authorisations must be reviewed according to your activity and circumstances.'],
['Formation','Can the formation process be prepared remotely?','Project scoping and file preparation can begin remotely. Signature, power of attorney and any physical presence requirements depend on your file and the organisations involved.'],
['Formation','What documents should I prepare?','For the first conversation, tell us about your activity, intended location, residency status and number of partners. Supporting documents will then be specified for the chosen structure. Our initial form does not request identity documents.'],
['Support','How long does company formation take?','Timing depends on the legal structure, completeness of the file, activity and administrative processing. An indicative schedule is reviewed after assessing your project; this website does not guarantee a fixed deadline.'],
['Fees','How much does Felexia support cost?','Each engagement receives a tailored quote. Scope, fees and any additional costs are specified before your commitment. No payment is requested in the contact form.'],
['Support','Can you support an existing company?','Yes. Needs may involve tax, management, company changes or administrative formalities. Tell us about your circumstances and desired outcome so we can define an appropriate engagement.'],
['Support','What is the difference between a subsidiary and a branch?','A subsidiary is a separate company majority-owned by a parent company. A branch is an establishment attached to its parent company. Legal, tax and organisational implications should be reviewed for each project.'],
['Contact','What happens during the first conversation?','You describe your project and needs. We clarify next steps and the possible scope of support. An appointment request is only confirmed following an exchange with the firm.'],
['Contact','Which languages can we use?','You can present your project in French, English or Arabic. Choose your preferred language in the form to help prepare our conversation.'],
['Data','How are form details used?','They help us understand your request and contact you. Do not submit identity documents, banking information or confidential records through the initial form. Read our privacy policy for further details.']
],
ar:[
['المواكبة','هل تواكبون المشاريع في جميع أنحاء المغرب؟','نعم. تواكب فيليكسيا رواد الأعمال والمستثمرين في جميع أنحاء المغرب. حدد مدينة الاستقرار واحتياجاتك لنحدد معاً كيفية المواكبة، عن بعد ووفق متطلبات ملفك.'],
['التأسيس','ما الشكل القانوني المناسب لمشروعي؟','يعتمد الاختيار على عدد الشركاء والنشاط ونظام الحكامة وآفاق التطوير. تستجيب الشركة ذات المسؤولية المحدودة، وصيغتها ذات الشريك الوحيد، وشركة المساهمة، واستقرار شركة أجنبية لاحتياجات مختلفة. يساعد اللقاء الأول على توضيح الخيارات المناسبة.'],
['التأسيس','هل يمكنني إنشاء مقاولة بالمغرب إذا كنت مقيماً بالخارج؟','نواكب المستثمرين الأجانب والمغاربة المقيمين بالخارج. تُدرس إمكانية الإنجاز والوثائق والتراخيص المحتملة بحسب نشاطك ووضعيتك.'],
['التأسيس','هل يمكن التحضير للتأسيس عن بعد؟','يمكن بدء تحديد المشروع وإعداد الملف عن بعد. تختلف متطلبات التوقيع والوكالة والحضور المحتمل بحسب الملف والجهات المعنية.'],
['التأسيس','ما الوثائق التي ينبغي تحضيرها؟','في اللقاء الأول، حدد نشاطك ومدينة الاستقرار ووضعية الإقامة وعدد الشركاء. ثم تُحدد قائمة الوثائق حسب الهيكلة المختارة. لا نطلب وثائق الهوية في الاستمارة الأولية.'],
['المواكبة','كم تستغرق عملية إنشاء المقاولة؟','تختلف المدة حسب الشكل القانوني واكتمال الملف والنشاط ومعالجة الإدارات. يُدرس الجدول التقديري بعد تحليل المشروع، ولا يضمن هذا الموقع أجلاً ثابتاً.'],
['الأتعاب','ما تكلفة مواكبة فيليكسيا؟','لكل مهمة عرض أتعاب مخصص. يُحدد النطاق والأتعاب والمصاريف المحتملة قبل التزامك. لا تُطلب أي دفعة في استمارة التواصل.'],
['المواكبة','هل تواكبون المقاولات القائمة؟','نعم. قد تشمل الاحتياجات الضرائب أو التدبير أو تغييرات الشركة أو الإجراءات الإدارية. قدم لنا وضعيتك والنتيجة المطلوبة لتحديد المهمة المناسبة.'],
['المواكبة','ما الفرق بين الشركة التابعة والفرع؟','الشركة التابعة كيان مستقل تملك شركة أم أغلبية رأسماله. أما الفرع فهو مؤسسة مرتبطة بالشركة الأم. يجب دراسة الآثار القانونية والضريبية والتنظيمية بحسب المشروع.'],
['التواصل','كيف يتم اللقاء الأول؟','تصف مشروعك واحتياجاتك، ثم نوضح الخطوات التالية والنطاق الممكن للمواكبة. لا يُؤكد الموعد إلا بعد التواصل مع المكتب.'],
['التواصل','بأي لغات يمكننا التواصل؟','يمكنك تقديم مشروعك بالفرنسية أو الإنجليزية أو العربية. اختر لغتك المفضلة في الاستمارة للتحضير للتواصل.'],
['البيانات','كيف تُستخدم معلومات الاستمارة؟','تُستخدم لفهم طلبك والتواصل معك. لا ترسل وثائق الهوية أو المعلومات البنكية أو الوثائق السرية عبر الاستمارة الأولية. راجع سياسة الخصوصية لمزيد من المعلومات.']
]};
export const structures=[
{slug:'sarl',label:'SARL',fr:['Entreprendre à plusieurs','Une société à responsabilité limitée, adaptée à de nombreux projets portés par plusieurs associés.','Les associés définissent ensemble le capital, la répartition des parts et les règles de fonctionnement dans les statuts.','Nombre d’associés, rôle du gérant, répartition du capital, objet social et siège.'],en:['Build with partners','A limited liability company suited to many projects involving several partners.','Partners define the capital, allocation of shares and operating arrangements in the articles.','Number of partners, manager’s role, allocation of capital, business purpose and registered office.'],ar:['المقاولة مع شركاء','شركة ذات مسؤولية محدودة تناسب العديد من المشاريع التي يحملها عدة شركاء.','يحدد الشركاء رأس المال وتوزيع الحصص وقواعد التسيير في النظام الأساسي.','عدد الشركاء ودور المسير وتوزيع رأس المال والغرض الاجتماعي والمقر.']},
{slug:'sarl-au',label:'SARL AU',fr:['Entreprendre seul','Une SARL constituée par un associé unique pour porter un projet en société.','Cette forme permet de distinguer l’organisation de la société de la personne de l’associé, dans le cadre prévu par la réglementation.','Activité, gérance, capital, adresse du siège et organisation du suivi administratif.'],en:['Start on your own','An SARL formed by a single member to operate a business through a company.','This structure distinguishes the company’s organisation from its member within the applicable regulatory framework.','Activity, management, capital, registered office and administrative organisation.'],ar:['المقاولة بشكل فردي','شركة ذات مسؤولية محدودة يؤسسها شريك وحيد لحمل مشروعه.','يتيح هذا الشكل التمييز بين تنظيم الشركة وشخص الشريك ضمن الإطار القانوني المعمول به.','النشاط والتسيير ورأس المال والمقر وتنظيم المتابعة الإدارية.']},
{slug:'sa',label:'SA',fr:['Structurer un projet d’envergure','La société anonyme répond à des besoins de structuration du capital et de gouvernance plus élaborés.','Le choix nécessite une analyse des actionnaires, des règles de gouvernance et des obligations propres à cette forme.','Actionnariat, financement, gouvernance et obligations de contrôle.'],en:['Structure a larger project','A public limited company addresses more elaborate capital and governance needs.','The choice requires a review of shareholders, governance arrangements and the specific obligations of this structure.','Shareholding, financing, governance and oversight obligations.'],ar:['هيكلة مشروع واسع','تستجيب شركة المساهمة لاحتياجات أكثر تقدماً في هيكلة رأس المال والحكامة.','يتطلب الاختيار دراسة المساهمين وقواعد الحكامة والالتزامات الخاصة بهذا الشكل.','المساهمون والتمويل والحكامة والتزامات المراقبة.']},
{slug:'sas',label:'SAS',fr:['Étudier une gouvernance adaptée','La société par actions simplifiée est une option à examiner selon la structure de votre projet.','Les règles applicables et l’organisation statutaire doivent être vérifiées avec un professionnel avant de retenir cette forme.','Profil des associés, gouvernance souhaitée et validation du cadre juridique applicable.'],en:['Explore tailored governance','A simplified joint-stock company is an option to review in light of your project structure.','Applicable rules and articles should be checked with a professional before selecting this structure.','Partner profiles, desired governance and verification of the applicable legal framework.'],ar:['دراسة حكامة ملائمة','شركة الأسهم المبسطة خيار يُدرس بحسب هيكلة مشروعك.','يجب التحقق من القواعد المنطبقة والتنظيم الأساسي مع مهني قبل اختيار هذا الشكل.','صفة الشركاء والحكامة المطلوبة والتحقق من الإطار القانوني المنطبق.']},
{slug:'filiale',label:'Filiale',fr:['Créer une entité locale','Une société marocaine détenue majoritairement par une société mère.','La filiale dispose d’une personnalité juridique distincte. Sa forme, ses liens avec le groupe et ses flux doivent être étudiés conjointement.','Documents de la société mère, organisation du groupe et besoins opérationnels au Maroc.'],en:['Establish a local entity','A Moroccan company majority-owned by a parent company.','A subsidiary has a separate legal personality. Its structure, group relationships and transactions should be considered together.','Parent company documents, group organisation and operational needs in Morocco.'],ar:['إنشاء كيان محلي','شركة مغربية تملك شركة أم أغلبية رأسمالها.','للشركة التابعة شخصية قانونية مستقلة. يجب دراسة شكلها وروابطها مع المجموعة وتدفقاتها معاً.','وثائق الشركة الأم وتنظيم المجموعة والاحتياجات التشغيلية بالمغرب.']},
{slug:'succursale',label:'Succursale',fr:['Prolonger une activité au Maroc','Un établissement au Maroc rattaché à une société existante à l’étranger.','La succursale ne constitue pas une personne morale distincte de sa société mère. Les responsabilités et implications fiscales appellent une analyse spécifique.','Documents de la société mère, activité locale, représentant et modalités d’implantation.'],en:['Extend your activity to Morocco','An establishment in Morocco attached to an existing foreign company.','A branch is not a separate legal entity from its parent. Responsibilities and tax implications require specific analysis.','Parent company documents, local activity, representative and establishment arrangements.'],ar:['توسيع النشاط إلى المغرب','مؤسسة بالمغرب مرتبطة بشركة قائمة بالخارج.','لا يشكل الفرع شخصاً معنوياً مستقلاً عن الشركة الأم. تتطلب المسؤوليات والآثار الضريبية دراسة خاصة.','وثائق الشركة الأم والنشاط المحلي والممثل وشروط الاستقرار.']}
];
export const structureName=(s,l)=>s.slug==='filiale'?({fr:'Filiale',en:'Subsidiary',ar:'شركة تابعة'}[l]):s.slug==='succursale'?({fr:'Succursale',en:'Branch',ar:'فرع'}[l]):s.label;
export const guides=[
{slug:'preparer-creation-entreprise',symbol:'01',icon:'building',fr:['CRÉATION D’ENTREPRISE','Préparer sa création d’entreprise au Maroc','Les questions à clarifier avant de constituer votre dossier.','4 min',[
['Commencer par l’activité','Décrivez précisément les produits ou services, les clients visés et la ville d’implantation. Certaines activités peuvent relever d’autorisations ou de conditions spécifiques : ce point doit être vérifié avant le lancement.'],
['Identifier les personnes et leur rôle','Précisez qui porte le projet, le nombre d’associés, leur situation de résidence et la répartition envisagée des responsabilités. Ces éléments alimentent le choix de la structure et la préparation des statuts.'],
['Préparer les étapes administratives','Le parcours peut notamment comprendre le certificat négatif, les statuts, les formalités liées au capital selon le cas, l’immatriculation, les identifiants et les publications. Les obligations sociales dépendent de la situation de l’entreprise.'],
['Distinguer les identifiants','Le Registre de Commerce, l’identifiant fiscal, l’ICE et l’identification CNSS répondent à des finalités différentes. L’ICE complète les autres identifiants ; il ne les remplace pas.'],
['Construire un dossier adapté','La liste des pièces est à confirmer selon la forme, les associés et l’activité. Commencez par un échange de cadrage avant de transmettre des documents sensibles.']]],en:['COMPANY FORMATION','Preparing to start a company in Morocco','The questions to clarify before putting your file together.','4 min',[
['Start with the activity','Describe the products or services, target customers and intended location. Some activities may require specific authorisations or conditions, which should be checked before launch.'],['Identify the people and their roles','Clarify the project owners, number of partners, residency status and intended responsibilities. These details inform the choice of structure and preparation of the articles.'],['Prepare the administrative stages','The process may include a negative certificate, articles, capital-related formalities where applicable, registration, identifiers and publications. Social obligations depend on the company’s circumstances.'],['Distinguish the identifiers','Commercial registration, tax identification, ICE and CNSS identification have different purposes. ICE complements the other identifiers; it does not replace them.'],['Build an appropriate file','Confirm the required documents for the structure, partners and activity. Begin with a scoping conversation before sharing sensitive documents.']]],ar:['إنشاء المقاولات','التحضير لإنشاء مقاولة بالمغرب','أسئلة ينبغي توضيحها قبل إعداد الملف.','4 دقائق',[
['ابدأ بالنشاط','حدد المنتجات أو الخدمات والعملاء المستهدفين ومدينة الاستقرار. قد تتطلب بعض الأنشطة تراخيص أو شروطاً خاصة يجب التحقق منها قبل الانطلاق.'],['حدد الأشخاص وأدوارهم','وضح حاملي المشروع وعدد الشركاء ووضعية إقامتهم والمسؤوليات المتوقعة. تساعد هذه المعلومات على اختيار الهيكلة وإعداد النظام الأساسي.'],['حضّر المراحل الإدارية','قد يشمل المسار الشهادة السلبية والنظام الأساسي وإجراءات رأس المال عند الاقتضاء والتسجيل والمعرفات والنشر. وتتوقف الالتزامات الاجتماعية على وضعية المقاولة.'],['ميّز بين المعرفات','للسجل التجاري والمعرف الضريبي والمعرف الموحد للمقاولة والتعريف لدى الصندوق الوطني للضمان الاجتماعي أغراض مختلفة. يكمل المعرف الموحد المعرفات الأخرى ولا يعوضها.'],['كوّن ملفاً ملائماً','تُؤكد قائمة الوثائق حسب الشكل القانوني والشركاء والنشاط. ابدأ بلقاء لتحديد الاحتياجات قبل مشاركة وثائق حساسة.']]]},
{slug:'investir-depuis-etranger',symbol:'02',icon:'globe',fr:['INVESTISSEMENT','Investir au Maroc depuis l’étranger','Les points de départ d’une implantation bien préparée.','3 min',[
['Définir le projet local','Votre implantation peut servir une activité commerciale, une prestation de services ou le développement d’un groupe. Précisez l’activité effectivement exercée au Maroc et les moyens nécessaires.'],['Comparer les options d’implantation','Une société indépendante, une filiale ou une succursale impliquent des organisations et des responsabilités différentes. L’analyse doit tenir compte de la société mère, des associés et des flux prévus.'],['Organiser les pièces et les échanges','Les documents provenant de l’étranger peuvent nécessiter des formalités de traduction ou d’authentification selon leur usage. Le cabinet précise les exigences applicables au dossier avant leur préparation.'],['Anticiper le démarrage','Au-delà de la constitution, préparez la domiciliation ou le siège, les échanges bancaires, les obligations fiscales et sociales ainsi que les outils de gestion. Les règles de change et les autorisations sectorielles sont à vérifier selon votre situation.']]],en:['INVESTMENT','Investing in Morocco from abroad','Starting points for a well-prepared establishment.','3 min',[
['Define the local project','Your establishment may support trading, services or group development. Specify the actual activity in Morocco and the resources it requires.'],['Compare establishment options','An independent company, subsidiary and branch involve different arrangements and responsibilities. Analysis should consider the parent company, partners and planned transactions.'],['Organise documents and communication','Documents from abroad may require translation or authentication depending on their use. The firm clarifies applicable requirements before preparation.'],['Anticipate the launch','Beyond incorporation, prepare the registered office, banking discussions, tax and social obligations and management tools. Foreign exchange rules and sector authorisations must be checked against your circumstances.']]],ar:['الاستثمار','الاستثمار بالمغرب انطلاقاً من الخارج','نقاط أساسية للتحضير الجيد للاستقرار.','3 دقائق',[
['حدد المشروع المحلي','قد يخدم استقرارك نشاطاً تجارياً أو خدماتياً أو تطوير مجموعة. حدد النشاط الفعلي بالمغرب والوسائل اللازمة له.'],['قارن خيارات الاستقرار','تنطوي الشركة المستقلة والشركة التابعة والفرع على تنظيم ومسؤوليات مختلفة. يجب أن تراعي الدراسة الشركة الأم والشركاء والتدفقات المرتقبة.'],['نظم الوثائق والتواصل','قد تحتاج الوثائق الصادرة من الخارج إلى ترجمة أو توثيق حسب استعمالها. يوضح المكتب المتطلبات المنطبقة قبل إعدادها.'],['استبق الانطلاق','إلى جانب التأسيس، حضّر المقر والتواصل البنكي والالتزامات الضريبية والاجتماعية وأدوات التدبير. يجب التحقق من قواعد الصرف والتراخيص القطاعية بحسب وضعيتك.']]]},
{slug:'organiser-gestion-entreprise',symbol:'03',icon:'chart',fr:['GESTION & FISCALITÉ','Les bons repères pour piloter son entreprise','Une organisation lisible pour accompagner le développement.','3 min',[
['Centraliser les documents utiles','Rassemblez les documents constitutifs, les références administratives et les contrats dans une organisation accessible aux seules personnes concernées. Prévoyez des sauvegardes adaptées.'],['Construire un calendrier adapté','Identifiez avec votre conseil les échéances réellement applicables à l’activité et à la situation de l’entreprise. Un calendrier générique ne remplace pas une analyse de vos obligations.'],['Suivre des indicateurs utiles','Suivez les recettes, les dépenses, les créances et les besoins de trésorerie selon une fréquence adaptée. Un petit nombre d’indicateurs compris et à jour vaut mieux qu’un tableau complexe peu utilisé.'],['Revoir l’organisation lorsque l’entreprise évolue','Une nouvelle activité, un associé supplémentaire ou une implantation peuvent modifier vos besoins. Anticipez les impacts administratifs, fiscaux et de gestion avant la décision.']]],en:['MANAGEMENT & TAX','Practical foundations for managing your business','Clear organisation to support business development.','3 min',[
['Centralise useful documents','Organise formation documents, administrative references and contracts so only relevant people can access them. Arrange suitable backups.'],['Build a relevant calendar','Identify with your adviser the deadlines that actually apply to your activity and circumstances. A generic calendar is not a substitute for a review of your obligations.'],['Monitor useful indicators','Track income, expenditure, receivables and cash needs at an appropriate frequency. A few understood, up-to-date indicators are more useful than a complex, rarely used dashboard.'],['Review organisation as the business evolves','A new activity, additional partner or establishment may change your needs. Anticipate administrative, tax and management implications before deciding.']]],ar:['التدبير والضرائب','أسس عملية لقيادة مقاولتك','تنظيم واضح لمواكبة التطوير.','3 دقائق',[
['اجمع الوثائق المفيدة','نظم وثائق التأسيس والمراجع الإدارية والعقود مع حصر الوصول في الأشخاص المعنيين. وفر نسخاً احتياطية ملائمة.'],['ابنِ تقويماً مناسباً','حدد مع مستشارك الآجال المنطبقة فعلياً على نشاطك ووضعيتك. لا يعوض التقويم العام دراسة التزاماتك.'],['تتبع مؤشرات مفيدة','تتبع المداخيل والمصاريف والمستحقات واحتياجات الخزينة بوتيرة مناسبة. مؤشرات قليلة مفهومة ومحدثة أفضل من لوحة معقدة نادراً ما تُستخدم.'],['راجع التنظيم عند تطور المقاولة','قد يغير نشاط جديد أو شريك إضافي أو موقع آخر احتياجاتك. استبق الآثار الإدارية والضريبية والتدبيرية قبل القرار.']]]}
];
export const legalContent={
fr:{
legal:[['Éditeur du site','Le site est présenté sous le nom commercial Felexia Conseils. Adresse de contact : Résidence Al Ihssane, Immeuble 3, Appartement 4, Mabrouka, Marrakech, Maroc. E-mail : hadigui.aziz@gmail.com. Bureau : +212 520 825 825. Mobile : +212 661 080 862. WhatsApp : +212 661 400 352.'],['Identification et hébergement','Pour toute question concernant l’identification juridique du cabinet ou l’hébergement de ce site, contactez Felexia aux coordonnées indiquées ci-dessus.'],['Contenus et propriété intellectuelle','Les éléments de marque Felexia proviennent des ressources du cabinet. Les textes de ce site sont des contenus d’information générale. Toute réutilisation des éléments protégés nécessite l’autorisation du titulaire des droits.'],['Crédit photographique','Photographies d’illustration : Alena Darmel, fauxels, Bia Limova, Mikhail Nilov, Edmond Dantès, Muharrem Alper et Sora Shimazaki / Pexels, utilisées sous licence Pexels. Ces images ne représentent ni les équipes, ni les clients, ni les locaux de Felexia.'],['Portée des informations','Les contenus ne constituent ni une consultation personnalisée ni un engagement de résultat. Les situations nécessitant l’intervention d’un professionnel habilité sont examinées dans le cadre de la mission.']],
privacy:[['Responsable et finalité','Felexia Conseils utilise les informations que vous transmettez pour examiner votre demande, préparer un échange et y répondre. Contact relatif aux données : hadigui.aziz@gmail.com.'],['Données demandées','Les formulaires peuvent recueillir votre nom, vos coordonnées professionnelles, votre pays de résidence, votre besoin et une description du projet. Les champs obligatoires sont signalés. Ne joignez pas de données bancaires, de documents d’identité ou d’informations confidentielles à cette première demande.'],['Transmission et destinataires','Lorsque l’envoi direct est activé, votre demande est transmise au cabinet par son prestataire de messagerie ou de traitement. Si cet envoi est indisponible, aucune confirmation d’envoi n’est affichée : vous pouvez choisir d’envoyer un message par votre messagerie ou WhatsApp, qui appliquent leurs propres conditions.'],['Conservation et droits','Les données sont conservées le temps nécessaire au traitement de la demande et, si une relation professionnelle est engagée, selon les obligations applicables à la mission. Vous pouvez demander l’accès, la rectification ou la suppression de vos données en écrivant au cabinet. Pour toute précision sur les modalités de traitement et vos droits au titre de la loi 09-08, contactez le cabinet.'],['Navigation et sécurité','Le site n’intègre pas de publicité, de suivi d’audience ni de stockage de formulaire dans votre navigateur. Les polices et les photographies sont hébergées avec le site. Les hébergeurs peuvent traiter les journaux techniques nécessaires à la sécurité.']],
terms:[['Objet du site','Ce site présente les activités de Felexia Conseils et permet de préparer une demande d’accompagnement. L’utilisation du site ne crée pas à elle seule une relation contractuelle de conseil.'],['Demande et devis','Les formulaires servent à exprimer un besoin. Une mission débute selon les conditions convenues avec le cabinet, après définition de son périmètre et de ses honoraires. Aucun prix forfaitaire ni paiement en ligne n’est proposé sur le site.'],['Rendez-vous','La date et le créneau renseignés constituent une préférence. Le rendez-vous n’est confirmé qu’après échange avec Felexia.'],['Informations générales','Les procédures, obligations et exigences peuvent évoluer. Les délais dépendent du dossier et des organismes concernés. Les contenus doivent être appréciés à la lumière de votre situation.'],['Liens et disponibilité','Les sites tiers restent sous la responsabilité de leurs éditeurs. Felexia peut faire évoluer les contenus ou interrompre temporairement le site pour maintenance. Pour une demande urgente, utilisez les coordonnées directes du cabinet.']],
cookies:[['Un site sans traceurs publicitaires','Ce site n’installe aucun cookie publicitaire ni outil de mesure d’audience. Aucun bandeau d’acceptation n’est donc nécessaire pour les fonctions actuellement proposées.'],['Préférences et formulaires','La langue figure dans l’adresse de la page. Les informations saisies restent dans le formulaire ouvert et ne sont pas enregistrées dans le stockage local du navigateur.'],['Services externes','Les liens WhatsApp, e-mail, carte et ressources externes vous conduisent vers d’autres services. Leurs propres politiques s’appliquent lorsque vous les ouvrez.']]
},
en:{
legal:[['Website publisher','This website is presented under the trading name Felexia Conseils. Contact address: Résidence Al Ihssane, Immeuble 3, Appartement 4, Mabrouka, Marrakech, Morocco. Email: hadigui.aziz@gmail.com. Office: +212 520 825 825. Mobile: +212 661 080 862. WhatsApp: +212 661 400 352.'],['Identification and hosting','For questions about the firm’s legal identity or website hosting, contact Felexia using the details above.'],['Content and intellectual property','Felexia branding comes from the firm’s resources. Website text provides general information. Reuse of protected material requires permission from the rights holder.'],['Photography credit','Illustrative photographs: Alena Darmel, fauxels, Bia Limova, Mikhail Nilov, Edmond Dantès, Muharrem Alper and Sora Shimazaki / Pexels, used under the Pexels licence. These images do not depict Felexia’s team, clients or premises.'],['Scope of information','Content is neither personalised advice nor a commitment to a particular outcome. Situations requiring an authorised professional are considered within the scope of the engagement.']],
privacy:[['Responsibility and purpose','Felexia Conseils uses information you submit to assess your request, prepare a conversation and respond. Data-related contact: hadigui.aziz@gmail.com.'],['Requested information','Forms may collect your name, professional contact details, country of residence, needs and a project description. Required fields are marked. Do not include banking data, identity documents or confidential information in this initial request.'],['Transmission and recipients','When direct submission is enabled, the request is transmitted to the firm through its email or processing provider. If submission is unavailable, no sent confirmation is displayed: you may choose to send a message through your email application or WhatsApp, which apply their own terms.'],['Retention and rights','Data is retained for the time necessary to handle the request and, if a professional relationship is established, according to applicable engagement obligations. You may request access, correction or deletion by contacting the firm. Contact the firm for details of processing arrangements and your rights under Law 09-08.'],['Browsing and security','The site includes no advertising, audience tracking or browser storage of form data. Fonts and photographs are hosted with the site. Hosting providers may process technical logs necessary for security.']],
terms:[['Website purpose','This website presents Felexia Conseils activities and helps prepare a support request. Using it does not, by itself, establish a contractual advisory relationship.'],['Requests and quotes','Forms express a need. An engagement begins under the conditions agreed with the firm after defining its scope and fees. No fixed prices or online payments are offered on this website.'],['Appointments','Dates and time slots entered are preferences. An appointment is confirmed only following an exchange with Felexia.'],['General information','Procedures, obligations and requirements may change. Timing depends on the file and the organisations involved. Content should be considered in light of your circumstances.'],['Links and availability','Third-party websites remain their publishers’ responsibility. Felexia may update content or temporarily interrupt the website for maintenance. For urgent requests, use the firm’s direct contact details.']],
cookies:[['No advertising trackers','This website sets no advertising cookies and uses no audience measurement tools. A consent banner is therefore unnecessary for the features currently provided.'],['Preferences and forms','The language is included in the page address. Entered information remains in the open form and is not saved to browser local storage.'],['External services','WhatsApp, email, map and external resource links lead to other services. Their own policies apply when you open them.']]
},
ar:{
legal:[['ناشر الموقع','يُقدم الموقع تحت الاسم التجاري Felexia Conseils. عنوان التواصل: إقامة الإحسان، عمارة 3، شقة 4، مبروكة، مراكش، المغرب. البريد الإلكتروني: hadigui.aziz@gmail.com. المكتب: ‎+212 520 825 825. المحمول: ‎+212 661 080 862. واتساب: ‎+212 661 400 352.'],['التعريف والاستضافة','للاستفسار عن الهوية القانونية للمكتب أو استضافة الموقع، تواصل مع فيليكسيا عبر البيانات أعلاه.'],['المحتوى والملكية الفكرية','مصدر عناصر علامة فيليكسيا هو موارد المكتب. تقدم نصوص الموقع معلومات عامة. تتطلب إعادة استخدام العناصر المحمية إذن صاحب الحقوق.'],['حقوق الصورة','صور توضيحية من Alena Darmel وfauxels وBia Limova وMikhail Nilov وEdmond Dantès وMuharrem Alper وSora Shimazaki / Pexels، مستخدمة بموجب ترخيص Pexels. لا تمثل هذه الصور فريق فيليكسيا أو عملاءها أو مقراتها.'],['نطاق المعلومات','لا تشكل المضامين استشارة شخصية أو التزاماً بنتيجة. تُدرس الحالات التي تستلزم تدخل مهني مؤهل ضمن نطاق المهمة.']],
privacy:[['المسؤول والغرض','تستخدم فيليكسيا المعلومات المرسلة لدراسة طلبك والتحضير للتواصل والرد عليه. للتواصل بشأن البيانات: hadigui.aziz@gmail.com.'],['البيانات المطلوبة','قد تجمع الاستمارات اسمك ووسائل التواصل المهني وبلد الإقامة والاحتياج ووصف المشروع. تُشار الحقول الإلزامية. لا ترسل بيانات بنكية أو وثائق هوية أو معلومات سرية في الطلب الأولي.'],['الإرسال والجهات المتلقية','عند تفعيل الإرسال المباشر، يُرسل طلبك إلى المكتب عبر مزود خدمة البريد أو المعالجة. إذا تعذر الإرسال فلا تظهر رسالة تأكيد: يمكنك اختيار إرسال رسالة عبر بريدك أو واتساب، وتطبق عليهما شروطهما الخاصة.'],['الاحتفاظ والحقوق','يُحتفظ بالبيانات للمدة اللازمة لمعالجة الطلب، وعند قيام علاقة مهنية وفق الالتزامات المنطبقة على المهمة. يمكنك طلب الوصول أو التصحيح أو الحذف بمراسلة المكتب. للاستفسار عن ترتيبات المعالجة وحقوقك بموجب القانون 09-08، تواصل مع المكتب.'],['التصفح والأمان','لا يتضمن الموقع إعلانات أو تتبعاً للجمهور أو تخزيناً لبيانات الاستمارات في المتصفح. تُستضاف الخطوط والصور مع الموقع. وقد يعالج المستضيفون السجلات التقنية اللازمة للأمان.']],
terms:[['غرض الموقع','يعرض الموقع أنشطة فيليكسيا ويساعد على إعداد طلب مواكبة. لا ينشئ استخدامه وحده علاقة تعاقدية للاستشارة.'],['الطلبات والعروض','تعبر الاستمارات عن احتياج. تبدأ المهمة وفق الشروط المتفق عليها مع المكتب بعد تحديد النطاق والأتعاب. لا يقدم الموقع أسعاراً جزافية أو أداءً عبر الإنترنت.'],['المواعيد','التاريخ والفترة المحددان تفضيلات أولية. لا يُؤكد الموعد إلا بعد التواصل مع فيليكسيا.'],['معلومات عامة','قد تتطور الإجراءات والالتزامات والمتطلبات. تتوقف الآجال على الملف والجهات المعنية. ينبغي تقييم المعلومات في ضوء وضعيتك.'],['الروابط والتوفر','تبقى المواقع الخارجية تحت مسؤولية ناشريها. قد تغير فيليكسيا المضامين أو توقف الموقع مؤقتاً للصيانة. للطلبات العاجلة، استعمل وسائل التواصل المباشرة.']],
cookies:[['بدون أدوات تتبع إعلانية','لا يثبت الموقع ملفات ارتباط إعلانية ولا يستخدم أدوات قياس الجمهور. لذلك لا تحتاج الوظائف الحالية إلى شريط موافقة.'],['التفضيلات والاستمارات','تظهر اللغة في عنوان الصفحة. تبقى المعلومات المدخلة في الاستمارة المفتوحة ولا تُحفظ في التخزين المحلي للمتصفح.'],['الخدمات الخارجية','تقود روابط واتساب والبريد والخريطة والمراجع إلى خدمات أخرى. تطبق سياساتها الخاصة عند فتحها.']]
}};
