// Editorial revision, not an automatically refreshed publication date.
export const editorialDate = '2026-09-22';
export const pick = (l, fr, en, ar) => ({fr,en,ar})[l];
const text = (fr,en,ar) => ({fr,en,ar});
export const editorial = {
  creation: {
    title:text('Créer une entreprise au Maroc en ligne | Felexia Conseils','Start a company in Morocco online | Felexia Conseils','تأسيس شركة في المغرب عن بُعد | Felexia Conseils'),
    h1:text('Créer une entreprise au Maroc en ligne, avec un cabinet à vos côtés','Start a company in Morocco online, with a firm by your side','أسّس شركتك في المغرب عن بُعد، بمواكبة مكتب استشاري'),
    intro:text('Démarrez votre dossier de création d’entreprise au Maroc à distance. Felexia Conseils vous accompagne dans le choix de la forme juridique, la préparation des documents et les formalités adaptées à votre situation.','Start your Moroccan company formation file remotely. Felexia Conseils helps you choose a legal structure, prepare documents and coordinate the formalities suited to your circumstances.','ابدأ ملف تأسيس شركتك في المغرب عن بُعد. تواكبك Felexia Conseils في اختيار الشكل القانوني وإعداد الوثائق وتنسيق الإجراءات المناسبة لوضعيتك.'),
    description:text('Créez votre société au Maroc avec Felexia Conseils : SARL, SARL AU, documents, formalités et accompagnement à distance. Demandez votre devis.','Start your company in Morocco with Felexia Conseils: SARL, single-member SARL, documents and remote support. Request a tailored quote.','أسّس شركتك في المغرب مع Felexia Conseils: شركة ذات مسؤولية محدودة، وثائق وإجراءات ومواكبة عن بُعد. اطلب عرضاً يناسب مشروعك.')
  },
  general: {
    slug:'guides/creation-entreprise',
    seoTitle:text('Créer une entreprise au Maroc : étapes','How to start a company in Morocco','كيف تؤسس شركة في المغرب'),
    description:text('Comment créer une entreprise au Maroc ? Activité, forme juridique, documents, signatures et étapes à préparer avant l’immatriculation de votre société.','How do you start a company in Morocco? Plan your activity, legal structure, documents, signatures and registration steps.','كيف تؤسس شركة في المغرب؟ حضّر النشاط والشكل القانوني والوثائق والتوقيعات ومراحل التسجيل قبل الانطلاق.'),
    title:text('Comment créer une entreprise au Maroc : étapes et documents','How to start a company in Morocco: steps and documents','كيف تؤسس شركة في المغرب: الخطوات والوثائق'),
    intro:text('Ce guide explique les décisions à prendre avant le dépôt d’un dossier : activité, associés, siège, documents et organisation des formalités. Il distingue les démarches de création des obligations qui commencent après l’immatriculation.','This guide covers the decisions to make before filing: activity, shareholders, registered office, documents and formalities. It separates formation steps from the obligations that begin after registration.','يشرح هذا الدليل القرارات المطلوبة قبل إيداع الملف: النشاط والشركاء والمقر والوثائق وتنظيم الإجراءات، ويميّز بين مراحل التأسيس والالتزامات التي تبدأ بعد التسجيل.')
  },
  online: {
    slug:'guides/creation-entreprise-en-ligne',
    seoTitle:text('Créer sa société à distance : guide Maroc','Remote company formation: Morocco guide','تأسيس شركة عن بُعد: دليل المغرب'),
    description:text('Préparez votre création d’entreprise au Maroc en ligne : pièces, suivi à distance, signatures et procurations. Comprenez les limites avant de démarrer.','Prepare company formation in Morocco online: documents, remote follow-up, signatures and powers of attorney. Understand the limits before starting.','حضّر تأسيس شركتك في المغرب عبر الإنترنت: الوثائق والمتابعة والتوقيعات والوكالات. افهم حدود الإجراءات عن بُعد قبل البدء.'),
    title:text('Création d’entreprise en ligne au Maroc : préparer son dossier à distance','Online company formation in Morocco: preparing your file remotely','تأسيس شركة بالمغرب عبر الإنترنت: إعداد الملف عن بُعد'),
    intro:text('Créer une société en ligne commence par une bonne préparation du dossier. Découvrez ce qui peut être échangé à distance et les vérifications à effectuer avant de prévoir une signature, une procuration ou un déplacement.','Online company formation starts with a well-prepared file. Learn what can be exchanged remotely and what to check before arranging a signature, power of attorney or journey.','يبدأ تأسيس الشركة عبر الإنترنت بإعداد ملف واضح. تعرّف على ما يمكن تبادله عن بُعد وما ينبغي التحقق منه قبل التوقيع أو إعداد وكالة أو برمجة تنقّل.')
  },
  sarl: {
    slug:'guides/creer-une-sarl-maroc',
    seoTitle:text('Créer une SARL au Maroc : démarches','Forming a SARL in Morocco: practical steps','تأسيس SARL بالمغرب: خطوات عملية'),
    description:text('Créer une SARL ou SARL AU au Maroc : associés, gérance, siège, capital et documents. Les décisions à préparer et les erreurs à éviter avant le dépôt.','Form a SARL or single-member SARL in Morocco: shareholders, management, registered office, capital and documents. Decisions and mistakes to consider.','تأسيس SARL أو SARL AU بالمغرب: الشركاء والتسيير والمقر ورأس المال والوثائق. قرارات للتحضير وأخطاء لتجنّبها قبل الإيداع.'),
    title:text('Créer une SARL au Maroc : associés, documents et démarches','Forming a SARL in Morocco: shareholders, documents and steps','تأسيس شركة ذات مسؤولية محدودة بالمغرب: الشركاء والوثائق والإجراءات'),
    intro:text('La SARL est une société à responsabilité limitée. La SARL AU correspond à sa forme à associé unique. Avant de déposer un dossier, clarifiez la répartition des parts, la gérance, le siège et les besoins financiers de votre activité.','A SARL is a limited liability company; a SARL AU is its single-member form. Before filing, clarify ownership, management, the registered office and the funding needs of your activity.','SARL هي شركة ذات مسؤولية محدودة، وSARL AU هي صيغتها ذات الشريك الوحيد. قبل إيداع الملف، حدّد توزيع الحصص والتسيير والمقر والحاجيات المالية للنشاط.')
  },
  foreign: {
    slug:'guides/mre-etranger',
    seoTitle:text('Créer au Maroc depuis l’étranger : guide MRE','Starting in Morocco from abroad: MRE guide','التأسيس في المغرب من الخارج: دليل الجالية'),
    description:text('MRE ou investisseur étranger : préparez votre société au Maroc depuis la France ou ailleurs. Documents, procuration, banque et coordination sur place.','Moroccan abroad or foreign investor? Prepare your company in Morocco from France or elsewhere: documents, powers of attorney, banking and local support.','مغربي بالخارج أو مستثمر أجنبي؟ حضّر شركتك بالمغرب من فرنسا أو غيرها: الوثائق والوكالة والبنك والتنسيق المحلي.'),
    title:text('Créer une entreprise au Maroc depuis la France ou l’étranger','Starting a company in Morocco from France or abroad','تأسيس شركة في المغرب انطلاقاً من فرنسا أو الخارج'),
    intro:text('Vous êtes MRE, non-résident ou investisseur étranger ? Préparez votre implantation au Maroc en tenant compte des documents étrangers, des signatures, des démarches bancaires et de la coordination sur place.','Are you a Moroccan living abroad, a non-resident or a foreign investor? Plan your Moroccan business with attention to foreign documents, signatures, banking and local coordination.','هل أنت مغربي مقيم بالخارج أو غير مقيم أو مستثمر أجنبي؟ حضّر مشروعك في المغرب مع مراعاة الوثائق الأجنبية والتوقيعات والإجراءات البنكية والتنسيق المحلي.')
  }
};

export function contentHelpers(l) {
  const t=(...args)=>pick(l,...args);
  const a=(route,...labels)=>`<a href="/${l}/${route}/">${t(...labels)}</a>`;
  const p=(...args)=>`<p>${t(...args)}</p>`;
  const section=(id,title,body)=>`<section id="${id}"><h2>${t(...title)}</h2>${body}</section>`;
  return {t,a,p,section};
}

export function creationSections(l) {
  const {t,a,p,section:s}=contentHelpers(l);
  return s('accompagnement',['Créer son entreprise avec Felexia Conseils','Start your business with Felexia Conseils','تأسيس شركتك مع Felexia Conseils'],p('Votre projet sert de point de départ : activité envisagée, nombre d’associés, lieu d’exercice et résidence des porteurs du projet. Ces éléments permettent de préparer une mission adaptée, plutôt qu’une liste de formalités identique pour tous. Vous connaissez le périmètre proposé avant de vous engager.','Your planned activity, shareholders, operating location and country of residence are the starting point. They help define a suitable engagement instead of treating every file alike. You receive the proposed scope before committing.','ننطلق من نشاطك المرتقب وعدد الشركاء ومكان المزاولة وبلد إقامة أصحاب المشروع، لتحديد مواكبة ملائمة بدل تطبيق الإجراءات نفسها على الجميع. تتعرّف على نطاق المهمة قبل الالتزام.'))+
  s('forme-juridique',['Quelle forme juridique choisir ?','Which legal structure should you choose?','ما الشكل القانوني المناسب؟'],`<h3>SARL</h3>${p('Pour un projet porté par plusieurs associés, les statuts organisent notamment les parts et la gérance. Le choix doit tenir compte de votre activité et du fonctionnement souhaité.','For a project with several shareholders, the articles organise ownership and management. Your activity and intended governance should guide the choice.','في المشروع الذي يجمع عدة شركاء، ينظّم النظام الأساسي الحصص والتسيير. ينبغي مراعاة طبيعة النشاط وطريقة اتخاذ القرارات.')}<h3>SARL AU</h3>${p('Si vous entreprenez seul, la SARL à associé unique mérite d’être étudiée. Elle reste une société, avec une gestion et des obligations propres, distinctes de votre situation personnelle.','If you are starting alone, consider the single-member SARL. It remains a company with its own management and obligations, separate from your personal circumstances.','إذا كنت تؤسس المشروع بمفردك، يمكن دراسة الشركة ذات الشريك الوحيد. وتبقى شركة لها تسيير والتزامات مستقلة عن وضعيتك الشخصية.')}<h3>${t('Autres formes selon votre projet','Other structures for your project','أشكال أخرى حسب المشروع')}</h3>${p('Un projet d’investissement, une activité réglementée ou une organisation particulière demande une analyse spécifique. Comparez les options avant la rédaction des statuts.','An investment project, regulated activity or specific ownership structure requires its own assessment. Compare the options before drafting the articles.','يحتاج المشروع الاستثماري أو النشاط المنظّم أو التنظيم الخاص إلى دراسة مناسبة. قارن الخيارات قبل إعداد النظام الأساسي.')}<p>${a('guides/creer-une-sarl-maroc','Comprendre les démarches de création d’une SARL','Understand the steps to form a SARL','تعرّف على إجراءات تأسيس SARL')} · ${a('formes-juridiques','Comparer les formes juridiques','Compare legal structures','قارن الأشكال القانونية')}</p>`)+
  s('documents',['Quels documents préparer ?','Which documents should you prepare?','ما الوثائق التي ينبغي إعدادها؟'],p('Préparez les pièces d’identité des associés et du gérant, plusieurs propositions de nom, une description de l’activité et les informations sur le siège envisagé. Selon le dossier, il faut aussi examiner le justificatif d’occupation, les projets de statuts, les pouvoirs des signataires et les documents d’une société associée.','Prepare identity documents for shareholders and the manager, proposed names, a description of the activity and the intended registered office. Depending on the file, occupancy evidence, draft articles, signatory powers and corporate shareholder documents must also be reviewed.','حضّر وثائق هوية الشركاء والمسيّر واقتراحات الاسم ووصف النشاط ومعلومات المقر المرتقب. وحسب الملف، تُدرس وثيقة شغل المقر ومشروع النظام الأساسي وصلاحيات الموقّعين ووثائق الشركة الشريكة.')+p('Cette liste est indicative. Le cabinet vous transmet une liste adaptée après le premier échange. Vérifiez la validité et la cohérence des noms et adresses avant toute signature ; les documents étrangers peuvent demander des formalités supplémentaires.','This is an indicative list. The firm provides a tailored checklist after the initial discussion. Check validity and consistency of names and addresses before signing; foreign documents may require additional formalities.','هذه لائحة استرشادية. يزوّدك المكتب بلائحة تناسب ملفك بعد التواصل الأول. تأكّد من الصلاحية وتطابق الأسماء والعناوين قبل التوقيع؛ وقد تتطلب الوثائق الأجنبية إجراءات إضافية.'))+
  s('distance',['Créer une entreprise au Maroc à distance','Start a company in Morocco remotely','تأسيس شركة في المغرب عن بُعد'],p('La présentation du projet, l’échange de pièces et le suivi avec le cabinet peuvent commencer en ligne. Cela ne signifie pas que toutes les formalités de votre dossier seront réalisables sans déplacement : signatures, procurations, exigences bancaires et contrôles administratifs doivent être confirmés selon votre situation.','Project discussions, document exchanges and follow-up can begin online. This does not mean every formality can be completed without travelling: signatures, powers of attorney, bank requirements and administrative checks must be confirmed for your circumstances.','يمكن بدء عرض المشروع وتبادل الوثائق والمتابعة مع المكتب عبر الإنترنت. ولا يعني ذلك أن جميع الإجراءات ممكنة دون تنقّل: يجب تأكيد متطلبات التوقيع والوكالة والبنك والمراقبة الإدارية حسب وضعيتك.')+`<p>${a('guides/creation-entreprise-en-ligne','Ce que vous pouvez préparer en ligne','What you can prepare online','ما يمكنك تحضيره عبر الإنترنت')}</p>`)+
  s('budget',['Combien coûte la création d’une entreprise au Maroc ?','How much does company formation in Morocco cost?','كم تبلغ تكلفة تأسيس شركة بالمغرب؟'],p('Le budget dépend de la forme juridique, de la situation des associés, des formalités nécessaires et des services retenus. Demandez un devis qui distingue les honoraires du cabinet, les frais administratifs et les prestations complémentaires éventuelles : siège, traductions ou démarches particulières.','The budget depends on the legal structure, shareholder circumstances, formalities and chosen services. Request a quote separating the firm’s fees, administrative expenses and possible extras such as a registered office, translations or specific procedures.','تتوقف الميزانية على الشكل القانوني ووضعية الشركاء والإجراءات والخدمات المختارة. اطلب عرضاً يميّز أتعاب المكتب عن المصاريف الإدارية والخدمات الإضافية المحتملة مثل المقر والترجمة والإجراءات الخاصة.')+`<p>${a('tarif/creation','Consulter les offres et demander un devis de création','Explore formation options and request a quote','اطّلع على عروض التأسيس واطلب تسعيرة')}</p>`)+
  s('delais',['Combien de temps prévoir ?','How much time should you allow?','ما المدة التي ينبغي توقعها؟'],p('Le calendrier dépend de la disponibilité des pièces, de leur conformité, des signatures et du traitement des organismes concernés. Aucun délai identique ne convient à tous les dossiers. Signalez vos contraintes de démarrage au premier échange et prévoyez une marge avant de prendre des engagements commerciaux.','Timing depends on document availability and completeness, signatures and processing by the relevant bodies. No single deadline fits every file. Explain your launch constraints early and allow a margin before making commercial commitments.','ترتبط المدة بتوفر الوثائق واكتمالها والتوقيعات ومعالجة الجهات المعنية. لا توجد مدة واحدة تناسب كل الملفات. وضّح موعد الانطلاق المستهدف منذ البداية واترك هامشاً قبل الالتزامات التجارية.'))+
  s('etranger',['Créer une société depuis la France ou l’étranger','Starting a company from France or abroad','تأسيس شركة انطلاقاً من فرنسا أو الخارج'],p('MRE et investisseurs non-résidents peuvent préparer leur dossier avec un interlocuteur au Maroc. Précisez votre pays de résidence, l’origine des fonds et les personnes habilitées à signer. La banque et les administrations déterminent les justificatifs nécessaires ; une procuration doit avoir un périmètre adapté.','Moroccans abroad and non-resident investors can prepare their file with a contact in Morocco. Specify your country of residence, funding origin and authorised signatories. Banks and administrations determine the required evidence; a power of attorney needs an appropriate scope.','يمكن للمغاربة المقيمين بالخارج والمستثمرين غير المقيمين إعداد ملفاتهم مع مخاطب في المغرب. حدّد بلد الإقامة ومصدر التمويل والأشخاص المخوّل لهم التوقيع. تحدد البنوك والإدارات الوثائق المطلوبة، ويجب أن يكون نطاق الوكالة مناسباً.')+`<p>${a('guides/mre-etranger','Préparer sa création d’entreprise depuis l’étranger','Plan your formation from abroad','حضّر تأسيس شركتك من الخارج')}</p>`)+
  s('apres-creation',['Préparer aussi le démarrage de l’activité','Plan the launch as well as the formation','حضّر لانطلاق النشاط أيضاً'],p('L’immatriculation ne termine pas l’organisation de votre entreprise. Anticipez le suivi comptable, les échéances fiscales, les obligations sociales lorsque vous recrutez et les éventuelles autorisations liées à l’activité. Le périmètre de cet accompagnement est distinct et doit être convenu.','Registration does not complete your business organisation. Plan bookkeeping, tax deadlines, social obligations when hiring and any activity-specific permits. Support for these matters has a separate scope to agree.','لا ينتهي تنظيم المقاولة بالتسجيل. استعد للمحاسبة والمواعيد الضريبية والالتزامات الاجتماعية عند التوظيف والتراخيص المرتبطة بالنشاط. ويُتفق بشكل مستقل على نطاق هذه المواكبة.')+`<p>${a('conseil-fiscal','Préparer le suivi fiscal','Plan tax support','حضّر المواكبة الضريبية')} · ${a('domiciliation','Étudier le siège social','Consider your registered office','ادرس مقر الشركة')} · ${a('guides/creation-entreprise','Lire le guide des démarches','Read the formation guide','اقرأ دليل الإجراءات')}</p>`);
}

// The four guides answer different questions. No city/keyword doorway pages.
const guideSections = {
  general: [
    [['Définir le projet avant les démarches','Define the project before filing','حدّد المشروع قبل الإجراءات'],['Décrivez précisément ce que vous vendrez, à qui et dans quel lieu. Identifiez les associés, leurs apports et la personne qui gérera la société. Si l’activité nécessite une autorisation, vérifiez ce point avant de signer un bail ou de fixer une date d’ouverture.','Describe what you will sell, to whom and where. Identify the shareholders, their contributions and the manager. If the activity requires authorisation, check this before signing a lease or setting an opening date.','حدّد ما ستبيعه ولمن وأين. عيّن الشركاء ومساهماتهم والمسيّر. إذا كان النشاط يحتاج إلى ترخيص، تحقّق من ذلك قبل توقيع عقد كراء أو تحديد موعد الافتتاح.']],
    [['Choisir la structure et préparer le nom','Choose the structure and prepare a name','اختر الشكل القانوني وحضّر الاسم'],['La structure juridique doit correspondre à votre organisation : entreprendre seul, s’associer ou implanter une société étrangère ne pose pas les mêmes questions. Préparez plusieurs propositions de dénomination. Le certificat négatif et la protection d’une marque répondent à des besoins différents ; ne les confondez pas.','Your legal structure should match your organisation: starting alone, with partners or through a foreign company raises different questions. Prepare several proposed names. A negative certificate and trademark protection serve different purposes; do not confuse them.','يجب أن يناسب الشكل القانوني تنظيم المشروع؛ فالتأسيس منفرداً أو مع شركاء أو عبر شركة أجنبية يطرح مسائل مختلفة. حضّر عدة أسماء. ولا تخلط بين الشهادة السلبية وحماية العلامة التجارية.']],
    [['Réunir des documents cohérents','Gather consistent documents','اجمع وثائق متطابقة'],['Rassemblez les identités, les coordonnées, les informations sur le siège et les pouvoirs des signataires. Les noms doivent correspondre d’un document à l’autre. Une société associée ou un document établi à l’étranger peut nécessiter des justificatifs spécifiques. Utilisez une liste adaptée à votre dossier plutôt qu’un modèle trouvé sans vérification.','Gather identities, contact details, registered-office information and signatory powers. Names should match across documents. Corporate shareholders or documents issued abroad may need specific evidence. Use a checklist tailored to your file rather than an unchecked template.','اجمع بيانات الهوية والتواصل والمقر وصلاحيات الموقّعين. يجب تطابق الأسماء بين الوثائق. وقد تتطلب الشركة الشريكة أو الوثائق الصادرة بالخارج إثباتات خاصة. اعتمد لائحة مناسبة لملفك بدل نموذج غير متحقّق منه.']],
    [['Préparer les statuts, signatures et formalités','Prepare articles, signatures and formalities','حضّر النظام الأساسي والتوقيعات والإجراءات'],['Les statuts organisent le fonctionnement de la société. Examinez l’objet, le siège, le capital, les parts et la gérance avant signature. Le circuit de dépôt et les formalités d’immatriculation sont ensuite déterminés selon la structure et le dossier. Conservez les justificatifs remis et vérifiez les informations figurant sur les documents obtenus.','The articles organise the company. Review its purpose, office, capital, shares and management before signing. Filing and registration formalities then depend on the structure and file. Keep the evidence provided and check the details on the issued documents.','ينظّم النظام الأساسي عمل الشركة. راجع الغرض والمقر ورأس المال والحصص والتسيير قبل التوقيع. ثم تُحدّد إجراءات الإيداع والتسجيل حسب الشكل القانوني والملف. احتفظ بالإثباتات وراجع المعلومات الواردة في الوثائق الصادرة.']],
    [['Éviter les erreurs au démarrage','Avoid launch mistakes','تجنّب أخطاء الانطلاق'],['Ne confondez pas honoraires, frais administratifs et capital de la société. Ne fixez pas un délai commercial sur la base d’une estimation non confirmée. Après l’immatriculation, organisez les pièces comptables, les échéances déclaratives et les autorisations propres à l’activité. Désignez la personne chargée de suivre ces obligations.','Do not confuse professional fees, administrative charges and company capital. Do not set commercial deadlines based on unconfirmed estimates. After registration, organise accounting records, filing deadlines and activity-specific permissions. Assign someone to follow these obligations.','لا تخلط بين الأتعاب والمصاريف الإدارية ورأس مال الشركة. ولا تلتزم بموعد تجاري اعتماداً على تقدير غير مؤكّد. بعد التسجيل، نظّم الوثائق المحاسبية والتصاريح والتراخيص الخاصة بالنشاط وحدّد المسؤول عن متابعتها.']]
  ],
  online: [
    [['Ce que vous pouvez préparer à distance','What you can prepare remotely','ما يمكنك إعداده عن بُعد'],['L’entretien initial, la description de l’activité, la collecte de copies et la vérification des informations peuvent commencer à distance. Préparez des fichiers lisibles et une liste des pièces déjà disponibles. Une copie transmise pour examen ne remplace pas automatiquement l’original requis au moment du dépôt.','Initial discussions, the activity description, copies and information checks can start remotely. Prepare readable files and list the documents already available. A copy sent for review does not automatically replace an original required for filing.','يمكن بدء النقاش الأول ووصف النشاط وجمع النسخ والتحقّق من المعلومات عن بُعد. حضّر ملفات واضحة ولائحة بالوثائق المتوفرة. ولا تعوّض النسخة المرسلة للفحص تلقائياً الأصل المطلوب عند الإيداع.']],
    [['Distinguer service en ligne et formalité administrative','Distinguish online support from official procedures','ميّز بين المواكبة الإلكترونية والإجراء الإداري'],['DirectEntreprise est le guichet électronique de création d’entreprise de l’OMPIC. La préparation avec un cabinet et l’utilisation d’un téléservice administratif sont deux choses distinctes. Les conditions d’accès, les pièces et les signatures requises doivent être vérifiées sur le service officiel et pour votre dossier.','DirectEntreprise is OMPIC’s electronic company formation portal. Preparing a file with an adviser and using an official online service are different things. Access conditions, documents and signatures must be checked with the official service for your file.','DirectEntreprise هي البوابة الإلكترونية لتأسيس المقاولات التابعة للمكتب المغربي للملكية الصناعية والتجارية. إعداد الملف مع مكتب استشاري واستخدام خدمة إدارية إلكترونية أمران مختلفان. يجب التحقّق من شروط الولوج والوثائق والتوقيعات حسب الملف.']],
    [['Confirmer signatures et procurations','Confirm signatures and powers of attorney','تأكّد من التوقيعات والوكالات'],['Avant de prévoir un parcours sans déplacement, demandez qui doit signer chaque pièce et sous quelle forme. Une procuration n’autorise que les actes qu’elle couvre et son acceptation dépend de l’organisme concerné. Les exigences de la banque doivent être confirmées séparément.','Before planning a process without travel, ask who must sign each document and in what form. A power of attorney only covers the acts within its scope, and acceptance depends on the relevant body. Confirm bank requirements separately.','قبل التخطيط لإجراءات دون تنقّل، اسأل عمّن يجب أن يوقّع كل وثيقة وبأي صيغة. لا تشمل الوكالة إلا الأعمال التي تنص عليها، ويتوقف قبولها على الجهة المعنية. تأكّد من المتطلبات البنكية بشكل مستقل.']],
    [['Suivre les étapes et protéger les pièces','Track progress and protect documents','تابع المراحل واحمِ الوثائق'],['Convenez avec votre interlocuteur des pièces attendues, de la prochaine action et du canal de transmission. Évitez d’envoyer des pièces d’identité dans un premier message non sollicité. Le formulaire Felexia sert à présenter votre projet ; le cabinet vous indique ensuite comment transmettre les documents nécessaires.','Agree with your contact on outstanding documents, the next action and the transmission channel. Avoid sending identity documents in an unsolicited first message. The Felexia form introduces your project; the firm then explains how to send the necessary documents.','اتفق مع مخاطبك على الوثائق المنتظرة والخطوة التالية وقناة الإرسال. تجنّب إرسال وثائق الهوية في رسالة أولى غير مطلوبة. يتيح نموذج Felexia تقديم مشروعك، ثم يوضّح المكتب كيفية إرسال الوثائق اللازمة.']],
    [['Prévoir un budget et un calendrier réalistes','Allow a realistic budget and schedule','ضع ميزانية وجدولاً زمنياً واقعيين'],['Le dépôt en ligne ne supprime ni l’examen du dossier ni les frais applicables. Demandez ce qui est compris dans le devis et ce qui reste à votre charge. Une pièce manquante, une signature ou une demande de complément peut modifier le calendrier annoncé.','Online filing does not remove review requirements or applicable charges. Ask what is included in the quote and what remains your responsibility. Missing documents, signatures or requests for additional information can change the schedule.','لا يلغي الإيداع الإلكتروني فحص الملف أو المصاريف المعمول بها. اسأل عما يتضمنه العرض وما يبقى على عاتقك. قد تغيّر وثيقة ناقصة أو توقيع أو طلب معلومات إضافية الجدول الزمني.']]
  ],
  sarl: [
    [['SARL et SARL AU : la question des associés','SARL and SARL AU: the shareholder question','SARL وSARL AU: مسألة الشركاء'],['La SARL AU permet un associé unique ; la SARL peut réunir plusieurs associés. La responsabilité limitée ne dispense pas le gérant de ses obligations et ne remplace pas l’analyse des garanties personnelles éventuellement demandées. Le choix doit porter sur l’organisation réelle du projet, pas seulement sur son nom.','A SARL AU has a single member; a SARL can have several shareholders. Limited liability does not remove a manager’s obligations or the need to assess any personal guarantees requested. Choose according to the real organisation of the project, not just the label.','تقوم SARL AU على شريك وحيد، بينما يمكن أن تضم SARL عدة شركاء. لا تعفي المسؤولية المحدودة المسيّر من التزاماته ولا تغني عن دراسة الضمانات الشخصية المطلوبة. اختر وفق التنظيم الفعلي للمشروع وليس التسمية فقط.']],
    [['Capital, parts et gérance','Capital, shares and management','رأس المال والحصص والتسيير'],['Décidez des apports, de leur répartition et des pouvoirs du gérant avant la rédaction des statuts. Distinguez le capital des frais de création et du budget nécessaire pour exploiter l’activité. Faites vérifier les formalités bancaires applicables au montant et à la nature des apports ; aucun montant type ne convient à tous les projets.','Decide contributions, ownership and management powers before drafting the articles. Separate capital from formation expenses and the working budget. Have the banking formalities checked for the amount and type of contributions; no standard amount suits every project.','حدّد المساهمات وتوزيعها وصلاحيات المسيّر قبل إعداد النظام الأساسي. ميّز رأس المال عن مصاريف التأسيس وميزانية التشغيل. تحقّق من الإجراءات البنكية حسب مبلغ المساهمات وطبيعتها؛ فلا يوجد مبلغ نموذجي يناسب كل المشاريع.']],
    [['Siège social et documents du dossier','Registered office and file documents','المقر ووثائق الملف'],['Le siège doit correspondre à une solution documentée : local ou domiciliation étudiée selon votre activité. Préparez les identités des associés et du gérant, le nom envisagé, les informations sur les apports et les pouvoirs de signature. Si un associé est une personne morale, précisez son identité juridique et son représentant.','The registered office needs documented arrangements: premises or a domiciliation solution suited to your activity. Prepare shareholder and manager identities, the proposed name, contributions and signing powers. For a corporate shareholder, identify the legal entity and its representative.','يحتاج المقر إلى حل موثّق: محل أو توطين يناسب النشاط. حضّر هويات الشركاء والمسيّر والاسم المرتقب وبيانات المساهمات وصلاحيات التوقيع. وإذا كان الشريك شخصاً معنوياً، حدّد هويته القانونية وممثله.']],
    [['De la préparation à l’immatriculation','From preparation to registration','من التحضير إلى التسجيل'],['Le parcours comprend l’étude de la structure, la préparation du nom et du siège, la rédaction et la signature des actes, puis les formalités de dépôt et d’immatriculation adaptées. Vérifiez ensuite les documents obtenus et les démarches complémentaires nécessaires au démarrage. Les exigences exactes sont à confirmer auprès des organismes compétents.','The process includes structure assessment, name and office preparation, drafting and signing, then the applicable filing and registration formalities. Check the issued documents and any additional launch procedures. Confirm exact requirements with the relevant bodies.','يشمل المسار دراسة الشكل وإعداد الاسم والمقر وصياغة العقود وتوقيعها، ثم إجراءات الإيداع والتسجيل المناسبة. راجع بعد ذلك الوثائق الصادرة والإجراءات التكميلية للانطلاق. تؤكَّد المتطلبات الدقيقة لدى الجهات المختصة.']],
    [['Obligations et erreurs fréquentes','Obligations and common mistakes','الالتزامات والأخطاء الشائعة'],['Organisez dès le départ la conservation des pièces, la comptabilité, les décisions des associés et le suivi des déclarations. Évitez les statuts copiés sans examen, une répartition des parts mal comprise ou la confusion entre les dépenses personnelles et celles de la société. La fiscalité et les obligations sociales doivent être étudiées selon l’activité.','Organise record retention, accounting, shareholder decisions and filing schedules from the start. Avoid unchecked copied articles, misunderstood ownership arrangements and mixing personal and company expenses. Tax and social obligations must be assessed for the activity.','نظّم منذ البداية حفظ الوثائق والمحاسبة وقرارات الشركاء ومتابعة التصاريح. تجنّب النظام الأساسي المنسوخ دون مراجعة وسوء فهم توزيع الحصص وخلط المصاريف الشخصية بمصاريف الشركة. وتُدرس الالتزامات الضريبية والاجتماعية حسب النشاط.']]
  ],
  foreign: [
    [['Préparer votre projet depuis votre pays de résidence','Prepare from your country of residence','حضّر من بلد إقامتك'],['Indiquez votre nationalité, votre pays de résidence, l’activité envisagée et si vous intervenez personnellement ou pour une société étrangère. Ces éléments permettent d’identifier les documents et les interlocuteurs utiles. Résider en France ou en Europe ne dispense pas des exigences marocaines ni de l’examen de votre situation dans le pays de résidence.','State your nationality, residence country, planned activity and whether you act personally or for a foreign company. These details help identify documents and contacts. Living in France or Europe does not remove Moroccan requirements or the need to assess your position in your residence country.','حدّد جنسيتك وبلد إقامتك والنشاط المرتقب وما إذا كنت تتصرف شخصياً أو باسم شركة أجنبية. تساعد هذه المعلومات على تحديد الوثائق والجهات المعنية. لا تعفي الإقامة في فرنسا أو أوروبا من المتطلبات المغربية أو دراسة وضعيتك في بلد الإقامة.']],
    [['Documents étrangers et signatures','Foreign documents and signatures','الوثائق الأجنبية والتوقيعات'],['Préparez les pièces d’identité et, pour une société associée, les documents relatifs à son existence et aux pouvoirs de son représentant. Demandez si des traductions, légalisations ou autres formalités sont nécessaires avant de les commander. Les exigences dépendent du pays d’émission, du document et du destinataire.','Prepare identity documents and, for corporate shareholders, evidence of existence and representative powers. Ask whether translations, legalisation or other formalities are needed before ordering them. Requirements depend on the issuing country, document and recipient.','حضّر وثائق الهوية، وبالنسبة للشركة الشريكة وثائق وجودها وصلاحيات ممثلها. اسأل عن الترجمة أو التصديق أو الإجراءات الأخرى قبل طلبها؛ فالمتطلبات تتوقف على بلد الإصدار والوثيقة والجهة المستقبلة.']],
    [['Procuration et présence au Maroc','Power of attorney and presence in Morocco','الوكالة والحضور في المغرب'],['Une procuration peut être envisagée pour certains actes. Son contenu, sa forme et son acceptation doivent être vérifiés avant signature. Demandez une confirmation séparée pour les démarches bancaires : l’accompagnement à distance ne garantit pas qu’aucune présence physique ne sera nécessaire.','A power of attorney may be considered for certain acts. Check its scope, form and acceptance before signing. Obtain separate confirmation for banking: remote support does not guarantee that physical attendance will never be required.','يمكن دراسة الوكالة لبعض الأعمال. تحقّق من مضمونها وصيغتها وقبولها قبل التوقيع. اطلب تأكيداً مستقلاً للإجراءات البنكية؛ فالمواكبة عن بُعد لا تضمن عدم الحاجة إلى الحضور الشخصي.']],
    [['Financement, banque et réglementation des changes','Funding, banking and exchange rules','التمويل والبنك وتنظيم الصرف'],['Documentez l’origine et le transfert des fonds avec votre banque. L’Office des Changes prévoit un régime de convertibilité pour les investissements étrangers financés en devises dans les conditions applicables. N’en déduisez pas un droit automatique au transfert sans justificatifs : conservez les preuves et faites examiner votre opération.','Document the source and transfer of funds with your bank. The Office des Changes provides a convertibility regime for foreign investments funded in foreign currency under applicable conditions. Do not assume an automatic transfer right without evidence: retain records and have your transaction assessed.','وثّق مصدر الأموال وتحويلها مع البنك. ينص مكتب الصرف على نظام قابلية التحويل للاستثمارات الأجنبية المموّلة بالعملة الأجنبية وفق الشروط المعمول بها. لا تفترض حقاً تلقائياً في التحويل دون إثباتات؛ احتفظ بالوثائق واطلب دراسة العملية.']],
    [['Coordonner le lancement et le suivi','Coordinate launch and follow-up','نسّق الانطلاق والمتابعة'],['Prévoyez le siège, un interlocuteur local, le suivi comptable et le calendrier des obligations. Faites préciser les services inclus et les frais complémentaires dans le devis. Avant de prendre un billet ou de signer un contrat, vérifiez les pièces encore attendues et les démarches qui demandent votre présence.','Plan the registered office, a local contact, accounting and compliance deadlines. Have included services and extra costs specified in the quote. Before booking travel or signing a contract, check outstanding documents and procedures requiring your presence.','خطّط للمقر والمخاطب المحلي والمحاسبة ومواعيد الالتزامات. اطلب تحديد الخدمات المشمولة والمصاريف الإضافية في العرض. قبل حجز السفر أو توقيع عقد، تحقّق من الوثائق المنتظرة والإجراءات التي تحتاج حضورك.']]
  ]
};

export function guideBody(key,l) {
  const {t,a,section:s}=contentHelpers(l);
  return guideSections[key].map(([heading,body],i)=>s(`seo-step-${i+1}`,heading,`<p>${t(...body)}</p>`)).join('')+
    s('seo-faq',['Questions pratiques','Practical questions','أسئلة عملية'],`<details class="seo-faq"><summary>${t('Dois-je attendre de réunir toutes les pièces pour commencer ?','Must I gather every document before starting?','هل يجب جمع جميع الوثائق قبل البدء؟')}</summary><p>${t('Vous pouvez commencer par clarifier le projet et identifier les pièces manquantes. Le dépôt du dossier dépend ensuite des documents et signatures requis.','You can begin by clarifying the project and identifying missing documents. Filing then depends on the required documents and signatures.','يمكن البدء بتوضيح المشروع وتحديد الوثائق الناقصة. ثم يتوقف إيداع الملف على الوثائق والتوقيعات المطلوبة.')}</p></details><details class="seo-faq"><summary>${key==='sarl'?t('Faut-il choisir un capital standard ?','Should I choose a standard capital amount?','هل أختار مبلغاً نموذجياً لرأس المال؟'):key==='foreign'?t('Un déplacement au Maroc est-il toujours évitable ?','Can travel to Morocco always be avoided?','هل يمكن دائماً تجنّب السفر إلى المغرب؟'):t('Le dépôt en ligne remplace-t-il toutes les signatures ?','Does online filing replace every signature?','هل يعوّض الإيداع الإلكتروني جميع التوقيعات؟')}</summary><p>${key==='sarl'?t('Le montant et les apports doivent correspondre à votre projet. Faites examiner les besoins de financement et les formalités applicables avant de finaliser les statuts.','The amount and contributions should suit your project. Review financing needs and applicable formalities before finalising the articles.','يجب أن يناسب المبلغ والمساهمات مشروعك. ادرس حاجيات التمويل والإجراءات المطبقة قبل إنهاء النظام الأساسي.'):t('Non. Les exigences de signature, de représentation et de présence sont à confirmer pour chaque démarche, notamment auprès de la banque et des organismes concernés.','No. Confirm signature, representation and attendance requirements for each step, particularly with the bank and relevant bodies.','لا. يجب تأكيد متطلبات التوقيع والتمثيل والحضور لكل إجراء، خصوصاً مع البنك والجهات المعنية.')}</p></details>`)+
    s('seo-next',['Pour préparer votre prochaine étape','Prepare your next step','حضّر خطوتك التالية'],`<p>${a('creation-entreprise','Être accompagné pour créer son entreprise au Maroc','Get support to start your company in Morocco','استفد من المواكبة لتأسيس شركتك في المغرب')}.</p><p>${a('tarif/creation','Comprendre les tarifs sur devis','Understand tailored pricing','فهم التسعير حسب المشروع')} · ${a(key==='sarl'?'guides/sarl-sarl-au':'guides/creer-une-sarl-maroc','SARL et SARL AU','SARL and single-member SARL','SARL وSARL AU')} · ${a(key==='foreign'?'guides/creation-entreprise-en-ligne':'guides/mre-etranger','Préparer un dossier à distance','Prepare a file remotely','إعداد الملف عن بُعد')}</p>`)+
    s('seo-sources',['Sources et points à vérifier','Sources and checks','المصادر والنقاط الواجب التحقّق منها'],`<p>${t('Repères généraux ; les exigences applicables sont à confirmer pour votre dossier auprès des organismes compétents.','General guidance; confirm the applicable requirements for your file with the relevant bodies.','معلومات عامة؛ تُؤكَّد المتطلبات المناسبة لملفك لدى الجهات المختصة.')}</p><ul><li><a href="https://www.ompic.ma/en/content/creation-and-business-life">OMPIC — ${t('création et vie de l’entreprise','business creation and life','تأسيس المقاولة وحياتها')}</a></li><li><a href="https://directentreprise-guichet.sys.ompic.ma/">DirectEntreprise — OMPIC</a></li>${key==='foreign'?'<li><a href="https://www.oc.gov.ma/fr/etrangers-non-residents/realisation-de-l-investissement-etranger-au-maroc">Office des Changes</a></li>':''}</ul>`);
}
